# Generated by Django 4.1.2 on 2022-10-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название района"
                    ),
                ),
            ],
            options={
                "verbose_name": "Район",
                "verbose_name_plural": "Районы",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название предприятия"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание предприятия")),
                (
                    "districts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organizations",
                        to="organizations.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название товара/услуги"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="organizations.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар/Услуга",
                "verbose_name_plural": "Товары/Услуги",
            },
        ),
        migrations.CreateModel(
            name="OrganizationProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_products",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_products",
                        to="organizations.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товары организации",
                "verbose_name_plural": "Товары организаций",
            },
        ),
        migrations.CreateModel(
            name="OrganizationNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Название сети предприятий",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="org_networks", to="organizations.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сеть организаций",
                "verbose_name_plural": "Сети организаций",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="organization_network",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizations",
                to="organizations.organizationnetwork",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="products",
            field=models.ManyToManyField(
                related_name="organizations",
                through="organizations.OrganizationProduct",
                to="organizations.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="Unique name for category"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationproduct",
            constraint=models.UniqueConstraint(
                fields=("product", "organization"),
                name="Unique product for organization",
            ),
        ),
    ]
